dist: trusty
sudo: required

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

install:
  - npm i -g npm@latest
  - npm install

script: npm test